name: CI Pipeline

on:
  push:
    branches:
      - improvements
      - main
  pull_request:
    branches:
      - main
      - improvements

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      # - name: Install Puppeteer dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -y install libnss3-dev

      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      # - name: Install Puppeteer dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -y install libnss3-dev

      - name: Install dependencies
        run: npm install

      # Run Puppeteer tests
      - name: Run Puppeteer tests
        run: npm test

      # Upload test results
      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: puppeteer-test-results
      #     path: ./test-results/
