name: Puppeteer Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libnss3-dev
          npm install chromedriver@119
          npm install -g mocha mochawesome
          npm install
          npm install selenium-webdriver
          sudo apt-get update && sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-archive-keyring.gpg && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list && sudo apt-get update && sudo apt-get install -y google-chrome-stable
      
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Puppeteer tests
        run: npm mocha Test/*.test.js
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-stable"

    env:
      CI: true